### ISSUE TITLE
Error while loading the component

### ISSUE THREAD

**Issue by lucagia** [shogunxam/Home-Assistant-custom-components-cfr-toscana#1]
After updating to Home Assistant 2021.12.1 the component generates this error:
Platform error sensor.cfr - cannot import name 'SPEED_MS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

**Comment by shogunxam** [comment]
Hi @lucagia, unfortunatelly I'm not using the latest version of HA. Could you please do a test for me?
Can you try to replace the line 16 in the file sensor.py
`from homeassistant.const import (CONF_NAME, STATE_UNKNOWN, TEMP_CELSIUS, LENGTH_METERS, SPEED_MS)`
with this one
`from homeassistant.const import (CONF_NAME, STATE_UNKNOWN, TEMP_CELSIUS, LENGTH_METERS, SPEED_METERS_PER_SECOND)`
and let me know if it's working?
Thx

**Comment by lucagia** [comment]
Great! It works..
Thx
