### ISSUE TITLE
l'entità non è numerica

### ISSUE THREAD

**Issue by nadinecross** [shogunxam/Home-Assistant-custom-components-cfr-toscana#10]
Dopo l'aggiornamento di HA al 2024.5.1 (provenendo 2024.4.3) non visualizzo più i dati della centralina del cfr.
"l'entità non è numerica"
Non so se devo fare qualcosa io, non ho trovato informazioni.

Grazie!

**Comment by shogunxam** [comment]
È probabile che, con il nuovo aggiornamento, abbiano cambiato qualcosa nella definizione delle entità. Appena ho un po' di tempo lo controllo.
Il 5 mag 2024, 17:42 +0200, Nadine ***@***.***>, ha scritto:

**Comment by shogunxam** [comment]
Riesci a portarmi eventuali errori nel log di home assistant? Quell' errore potrebbe derivare dal fatto che l'entità non è stata caricata.

**Comment by nadinecross** [comment]
Buongiorno e grazie! Perdonami ma ieri scrivevo dal cellulare, ecco qui i vari log che ho trovato:

`Registratore: custom_components.cfr.sensor
Fonte: custom_components/cfr/sensor.py:290
Integrazione: cfr ([documentazione](https://github.com/shogunxam/Home-Assistant-custom-components-cfr-toscana))
Prima occorrenza: 5 maggio 2024 alle ore 17:21:41 (223 occorrenze)
Ultima registrazione: 06:56:29

Updater loop unexpectedly ended (station:TOS11000063 dataType:anemo) restarts in 60 seconds
Updater loop unexpectedly ended (station:TOS11000063 dataType:igro) restarts in 60 seconds
Updater loop unexpectedly ended (station:TOS11000063 dataType:termo) restarts in 60 seconds
Updater loop unexpectedly ended (station:TOS11000063 dataType:pluvio) restarts in 60 seconds`

-----------------------

`Registratore: homeassistant.helpers.frame
Fonte: helpers/frame.py:190
Prima occorrenza: 5 maggio 2024 alle ore 17:21:41 (226 occorrenze)
Ultima registrazione: 06:56:29

Detected that custom integration 'cfr' calls async_create_task from a thread at custom_components/cfr/sensor.py, line 106: self.async_schedule_update_ha_state(True), please report it to the author of the 'cfr' custom integration
Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
Detected that custom integration 'dpc' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/dpc/__init__.py, line 73: hass.async_add_job(hass.config_entries.async_forward_entry_setup(entry, platform)), please create a bug report at https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/issues
Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues`

-----------------------

`Registratore: py.warnings
Fonte: custom_components/cfr/sensor.py:291
Integrazione: cfr ([documentazione](https://github.com/shogunxam/Home-Assistant-custom-components-cfr-toscana))
Prima occorrenza: 5 maggio 2024 alle ore 17:22:41 (14 occorrenze)
Ultima registrazione: 00:09:07

/config/custom_components/cfr/sensor.py:291: RuntimeWarning: coroutine 'Entity.async_update_ha_state' was never awaited time.sleep(60)`

-----------------------

`Registratore: homeassistant.const
Fonte: helpers/deprecation.py:206
Prima occorrenza: 5 maggio 2024 alle ore 17:21:40 (3 occorrenze)
Ultima registrazione: 5 maggio 2024 alle ore 17:21:40

TEMP_CELSIUS was used from cfr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'cfr' custom integration
LENGTH_METERS was used from cfr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please report it to the author of the 'cfr' custom integration
SPEED_METERS_PER_SECOND was used from cfr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.METERS_PER_SECOND instead, please report it to the author of the 'cfr' custom integration`

**Comment by shogunxam** [comment]
A vedere dai log mi sa che devo sistemare un po' di cose. Mi ci vorrà un po' di tempo. Guardo se riesco nel fine settimana.
Il 6 mag 2024, 07:07 +0200, Nadine ***@***.***>, ha scritto:

**Comment by nadinecross** [comment]
> A vedere dai log mi sa che devo sistemare un po' di cose. Mi ci vorrà un po' di tempo. Guardo se riesco nel fine settimana. Il 6 mag 2024, 07:07 +0200, Nadine ***@***.***>, ha scritto:
> […](#)
> Buongiorno e grazie! Perdonami ma ieri scrivevo dal cellulare, ecco qui i vari log che ho trovato: `Registratore: custom_components.cfr.sensor Fonte: custom_components/cfr/sensor.py:290 Integrazione: cfr (documentazione) Prima occorrenza: 5 maggio 2024 alle ore 17:21:41 (223 occorrenze) Ultima registrazione: 06:56:29 Updater loop unexpectedly ended (station:TOS11000063 dataType:anemo) restarts in 60 seconds Updater loop unexpectedly ended (station:TOS11000063 dataType:igro) restarts in 60 seconds Updater loop unexpectedly ended (station:TOS11000063 dataType:termo) restarts in 60 seconds Updater loop unexpectedly ended (station:TOS11000063 dataType:pluvio) restarts in 60 seconds` `Registratore: homeassistant.helpers.frame Fonte: helpers/frame.py:190 Prima occorrenza: 5 maggio 2024 alle ore 17:21:41 (226 occorrenze) Ultima registrazione: 06:56:29 Detected that custom integration 'cfr' calls async_create_task from a thread at custom_components/cfr/sensor.py, line 106: self.async_schedule_update_ha_state(True), please report it to the author of the 'cfr' custom integration Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues Detected that custom integration 'dpc' calls async_add_job, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/dpc/init.py, line 73: hass.async_add_job(hass.config_entries.async_forward_entry_setup(entry, platform)), please create a bug report at https://github.com/caiosweet/Home-Assistant-custom-components-DPC-Alert/issues Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues` `Registratore: py.warnings Fonte: custom_components/cfr/sensor.py:291 Integrazione: cfr (documentazione) Prima occorrenza: 5 maggio 2024 alle ore 17:22:41 (14 occorrenze) Ultima registrazione: 00:09:07 /config/custom_components/cfr/sensor.py:291: RuntimeWarning: coroutine 'Entity.async_update_ha_state' was never awaited time.sleep(60)` `Registratore: homeassistant.const Fonte: helpers/deprecation.py:206 Prima occorrenza: 5 maggio 2024 alle ore 17:21:40 (3 occorrenze) Ultima registrazione: 5 maggio 2024 alle ore 17:21:40 TEMP_CELSIUS was used from cfr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'cfr' custom integration LENGTH_METERS was used from cfr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.METERS instead, please report it to the author of the 'cfr' custom integration SPEED_METERS_PER_SECOND was used from cfr, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfSpeed.METERS_PER_SECOND instead, please report it to the author of the 'cfr' custom integration` — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Grazie mille!

**Comment by nadinecross** [comment]
Perfettamente funzionante, grazie ancora :D
