### ISSUE TITLE
l'entità non è numerica, ancora

### ISSUE THREAD

**Issue by nadinecross** [shogunxam/Home-Assistant-custom-components-cfr-toscana#13]
Dal 26/10 poco prima della mezzanotte, non ho fatto aggiornamenti di HA, mi sa che hanno ricambiato qualcosa al CFR oppure mi si è ingrippato HA... Dopo essermi accorta dell'errore ho aggiornato da 2024.10.3 a 2024.10.4 ma non è servito.

LOG:

Registratore: custom_components.cfr.sensor
Fonte: custom_components/cfr/sensor.py:279
Integrazione: cfr ([documentazione](https://github.com/shogunxam/Home-Assistant-custom-components-cfr-toscana))
Prima occorrenza: 19:31:54 (8 occorrenze)
Ultima registrazione: 19:32:58

Error parsing data from url http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=igro&1730140311.7576318 (station:TOS11000063 dataType:igro)
Error parsing data from url http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=termo&1730140374.7457623 (station:TOS11000063 dataType:termo)
Error parsing data from url http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=anemo&1730140374.9285784 (station:TOS11000063 dataType:anemo)
Error parsing data from url http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=igro&1730140375.207505 (station:TOS11000063 dataType:igro)
Error parsing data from url http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=pluvio&1730140374.7748516 (station:TOS11000063 dataType:pluvio)

**Comment by shogunxam** [comment]
Ho fatto un fix questa mattina. Lo hai già provato? Hanno cambiato il valore di una stringa e falliva il parser della regular expression
Il 28 ott 2024, 19:42 +0100, Nadine ***@***.***>, ha scritto:

**Comment by shogunxam** [comment]
Mi ero dimenticato di aggiornare il manifest, ora dovrebbe comparire l'aggiornamento anche su HACS

**Comment by nadinecross** [comment]
Fantastico, non mi segnava l'aggiornamento ma dopo il tuo precedente post ho riscaricato e funziona perfettamente!
Oramai la tua è una delle integrazioni che mi piacciono di più su HA, non posso farne a meno 👍

Grazie mille per tutto!

**Comment by shogunxam** [comment]
Lieto che ti sia di aiuto.
Visto che ti funziona chiudo l'issue come resolved
