### ISSUE TITLE
wind attribute

### ISSUE THREAD

**Issue by lucagia** [shogunxam/Home-Assistant-custom-components-cfr-toscana#3]
Hi,
I can't read the wind gust attribute in HA anymore.

**Comment by shogunxam** [comment]
Hi, I need some more information.
Have you updated HA? if yes which version are you using?
Which station Code are you using (perhaps the information is no more available on line)?
Do you have some errors in the HA logs?

**Comment by lucagia** [comment]
yes, I have updated HA to the version 2022.4.0
I use TOS01001269
In the graph https://cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS01001269&title=La%20Ferruccia%20-%20(Agliana)&type=anemo i can find wind gust and direction

**Comment by nadinecross** [comment]
Same situation since update 2022.4.0 with station TOS11000063. In log:

Error while processing template: Template("{{ ((states.sensor.vento.attributes.raffica)|float * 3.6)|round(1) }}")
Error while processing template: Template("{{ ((states.sensor.vento.attributes.direzione)|float)|round(0) }}")

**Comment by shogunxam** [comment]
Hi, @lucagia , @nadinecross  
please let me know if the new release resolve your problems. In case close this issue.

**Comment by lucagia** [comment]
it works
