### ISSUE TITLE
Rain sensor

### ISSUE THREAD

**Issue by lucagia** [shogunxam/Home-Assistant-custom-components-cfr-toscana#5]
Hi Shogunxam, i'm here again.
i am using rain sensor TOS01001269.
I notice a mismatch between the data provided by: https://cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS01001269&title=La%20Ferruccia%20-%20(Agliana)&type=pluvio and the data saved in HA.
The data recorded by HA is delayed at least one hour compared to what is published by the CFR site, moreover the accumulated precipitations assume different values ​​compared to CFR
![image](https://user-images.githubusercontent.com/80551550/164966324-456fe1dd-7caf-4a60-9085-4561d6bc2d57.png)
I specify that I do not do any operation on the rain data I collect from CFR

**Comment by shogunxam** [comment]
Hi @lucagia the hours' mismatch could be due to the day light saving time. I'm not sure the station uses it.

**Comment by shogunxam** [comment]
Hi @lucagia I can confirm the time in the graph reported by the cfr.toscana.it site doesn't consider the Day Light Saving time as you can guess from the main page of the web site.
![image](https://user-images.githubusercontent.com/21304551/165279809-d9927641-3a1d-4524-8e8d-38574f0d7fe5.png)

**Comment by lucagia** [comment]
Thanks for the quick reply.
I understood that the cumulative rain data provided by CFR always refers to midnight of the previous day.
