### ISSUE TITLE
Mareography data?

### ISSUE THREAD

**Issue by lucagia** [shogunxam/Home-Assistant-custom-components-cfr-toscana#6]
Hi, is it possible to integrate the mareography data?

https://www.cfr.toscana.it/index.php?IDS=42&IDSS=282

Thank you

**Comment by shogunxam** [comment]
Hi @lucagia I have take a look to the page but it seems the server API returns only the graph and not the data used to create it.
For this reason I cannot integrate it in the component.

**Comment by lucagia** [comment]
Ok, thank you for your time
