### ISSUE TITLE
connection time out

### ISSUE THREAD

**Issue by nadinecross** [shogunxam/Home-Assistant-custom-components-cfr-toscana#7]
Dopo aver aggiornato Home Assistant Core dalla 2023.2.1 alla 2023.2.5 non mi funziona più il cfr (ma potrei aver fatto io qualcosa di sbagliato...?). 

Log:

Dettagli registro (ERRORE)
Questo errore ha avuto origine da un'integrazione personalizzata.
Logger: custom_components.cfr.sensor
Source: custom_components/cfr/sensor.py:227
Integration: cfr ([documentation](https://github.com/shogunxam/Home-Assistant-custom-components-cfr-toscana))
First occurred: 25 febbraio 2023 alle ore 20:43:06 (22507 occurrences)
Last logged: 07:04:02

Connection to the site timed out at URL http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=igro&1677391435.8897471
Connection to the site timed out at URL http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=termo&1677391439.4197574
Connection to the site timed out at URL http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=pluvio&1677391440.472558
Connection to the site timed out at URL http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=igro&1677391441.1372495
Connection to the site timed out at URL http://www.cfr.toscana.it/monitoraggio/dettaglio.php?id=TOS11000063&type=anemo&1677391432.5213828

**Comment by Dim-1** [comment]
Stesso problema, ma nel mio caso non mi sembra essere coinciso con l'aggiornamento. Da 3 giorni l'integrazione non mi raccoglie dati della stazione meteo di San Miniato, da 1 giorno di un'altra stazione vicino che nel frattempo funzionava.

**Comment by shogunxam** [comment]
Così a prima vista sembra un problema di connessione con il sito. Sfortunatamente al momento sono influenzato, appena mi riprendo controllo. Nel caso fatemi sapere se ha ripreso a funzionare

**Comment by Dim-1** [comment]
Stranamente mi ha ripreso a comunicare una delle 2 stazioni meteo che seguo, cioè San Miniato Poggio al Pino. Invece San Miniato cimitero non comunica: il log da lo stesso responso di quanto già comunicato e scritto dall' utente che ha iniziato questo post.

**Comment by ZioTitanok** [comment]
Stesso problema anche per me, ma non sono sicuro al 100% che sia coinciso con l'aggiornamento.
Le stazioni che seguo, Montopoli (Temp, wind, humidity e pluvio), Pontedera (idro) e Fuceccio (idro) sembrano però tutte regolarmente funzionanti.

**Comment by shogunxam** [comment]
Come ho scritto in precedenza quell'errore è ritornato quando urlib non riesce, per un motivo, o per un altro, a recuperare i dati dal server. 
Se riuscite fate una prova alzando il timeout alla riga 223 del sensor.py portandolo da 10 a 30, ma non sono sicuro risolva.
La linea è questa
with urllib.request.urlopen(req,timeout=10) as response

**Comment by ZioTitanok** [comment]
> La linea è questa
with urllib.request.urlopen(req,timeout=10) as response

Impostato a 30 e riavviato. In serata vi faccio sapere com'è andata. Intanto, grazie per il suggerimento.

**Comment by shogunxam** [comment]
Grazie @ZioTitanok, comunque per la cronaca ho pure io quegli errori nei log, ma ad occhio dai grafici mi pare che comunque prima o poi riesca ad accedere. Visto che oggi sto un po' meglio vedo di darci un occhio come si deve

**Comment by Dim-1** [comment]
Con la modifica che ci hai suggerito, a me adesso funziona. Vediamo più avanti se 30 sec sono sempre sufficienti. Grazie mille per il lavoro che fai.

**Comment by shogunxam** [comment]
Mi sfugge perché non bastino 10 secondi, I link si aprono in una frazione di secondo da browser. Forse nel mio caso il problema è il Raspberry che non riesce a far tutto visto che USB e network sono sul solito bus

**Comment by nadinecross** [comment]
Grazie, ho aggiornato e funziona tutto!

**Comment by ZioTitanok** [comment]
Confermo che anche per me [HassOS su Proxmox su Dell Optiplex] il timeout impostato su 30 sembra aver funzionato correttamente per tutta la giornata su tutte le stazioni che ho configurato. Mi chiedo cosa sia cambiato improvvisamente per far nascere questo problema!

PS: Colgo l'occasione per ringraziare nuovamente @shogunxam per il lavoro svolto e per la soluzione.

**Comment by shogunxam** [comment]
Ho rifatto una release in cui ho aggiunto la possibilità di configurare il timeout direttamente nel sensore, se non viene indicato, di default è settato a 30 secondi.
Spero che questo risolva eventuali problemi futuri.
